---
title: "populationDynamics"
author: "Virgile Baudrot"
date: "14 octobre 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(trophToxNTO) # Package for ordinary differential equations
library(gridExtra)
library(tibble)
library(dplyr)
library(tidyr)
```


```{r param,echo=FALSE,warning=FALSE,include=FALSE}
times <- seq(from=0, to = 50*365, length = 50*365) #  30*5 = 5 months 

params <- pars(n=1,
               LD.50.V = 2,
               LD.50.M = 2,
               LD.50.F = 2,
               H.V = 4,
               H.M = 4,
               H.F = 4,
               days.to.die.V = 5, 
               days.to.die.M = 5,
               days.to.die.F = 5)

init.p <- init(params$n)
```

# With foxes

----------------------------------------- CONTROL

## a) Model 0-0


```{r model.output_0.0, echo=FALSE,warning=FALSE,comment=FALSE,message=FALSE, cache=TRUE}
# --------------------------- Modelisation -------------------
model.output_0.0 = ode(y=init.p,
                    times,
                    ode.broma.tritrophic, 
                    parms = params)
# --------------------------- Plot-------------------
graph_0.0 <- graphique_3(params$n,times,model.output_0.0)
graph_0.0
```

## b) Model 500-20

```{r model.output_500.20, cache=TRUE}
# --------------------------- EVENEMENTS -------------------
root.event=condition(Vole.Level=500,Broma.Level=20*50)[[1]] # kg * mg/kg
event.func=condition(Vole.Level=500,Broma.Level=20*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_500.20 = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

graph_500.20 <- graphique_3(params$n,times,model.output_500.20)
graph_500.20
```


## c) Model 250-20



```{r model.output_250.20, cache=TRUE}
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=250,Broma.Level=20*50)[[1]]
event.func = condition(Vole.Level=250,Broma.Level=20*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_250.20 = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

graph_250.20 <- graphique_3(params$n,times,model.output_250.20)
graph_250.20
```


## d) Model 250-7.5

```{r model.output_250.7.5, cache=TRUE}
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=250,Broma.Level=7.5*50)[[1]]
event.func = condition(Vole.Level=250,Broma.Level=7.5*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_250.7.5 = ode(y=init.p,
                   times,
                   ode.broma.tritrophic,
                   # ode.broma.tritrophic_2nd, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)
graph_250.7.5 <-graphique_3(params$n,times,model.output_250.7.5)
graph_250.7.5
```

## e) Model 50-7.5

```{r model.output_50.7.5, cache=TRUE}
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=50,Broma.Level=7.5*50)[[1]]
event.func = condition(Vole.Level=50,Broma.Level=7.5*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_50.7.5 = ode(y = init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

graph_50.7.5 <- graphique_3(params$n,times,model.output_50.7.5)
graph_50.7.5
```

# PLOT

### Foxes and Mustelids


```{r}
## INITIAL VALUE
# scale_fun_F <- function(df){
#   df[df$time == 0, "D.F_"]
# }
# scale_fun_M <- function(df){
#   df[df$time == 0, "D.M_"]
# }
## SCALE WITH MAXIMAL
scale_fun_F <- function(df){
  max(df$D.F_)
}
scale_fun_M <- function(df){
  max(df$D.M_)
}
```


```{r}
df_tab <- as.data.frame(model.output_0.0) %>%
  select(time, D.F_, D.M_) %>%
  mutate(group = "0.0",
         ID_group = "a")
D.F_scale_0.0 = scale_fun_F(df_tab)
D.M_scale_0.0 = scale_fun_M(df_tab)

df_tab$Foxes = df_tab$D.F_ / D.F_scale_0.0
df_tab$Mustelids = df_tab$D.M_ / D.M_scale_0.0

plot(df_tab$time, df_tab$Foxes)
plot(df_tab$time, df_tab$Mustelids)

df_plot_0.0_MF <- df_tab %>%
  gather(Species, ratioVar, c('Foxes', 'Mustelids'))

plot_0.0_MF <- ggplot(data = df_plot_0.0_MF) + theme_minimal() +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="time in year")+
  scale_color_manual(values = c("black", "grey70")) +
  labs(y = "Rate of variation of densities") +
  geom_line(aes(x = time, y = ratioVar, color = Species))
plot_0.0_MF
```

```{r}
df_tab <- as.data.frame(model.output_500.20) %>%
  select(time, D.F_, D.M_) %>%
  mutate(group = "500.20",
         ID_group = "b")
D.F_scale_500.20 = scale_fun_F(df_tab)
D.M_scale_500.20 = scale_fun_M(df_tab)

df_tab$Foxes = df_tab$D.F_ / D.F_scale_500.20
df_tab$Mustelids = df_tab$D.M_ / D.M_scale_500.20

plot(df_tab$time, df_tab$Foxes)
plot(df_tab$time, df_tab$Mustelids)

df_plot_500.20_MF <- df_tab %>%
  gather(Species, ratioVar, c('Foxes', 'Mustelids'))

plot_500.20_MF <- ggplot(data = df_plot_500.20_MF) + theme_minimal() +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="time in year")+
  scale_color_manual(values = c("black", "grey70")) +
  labs(y = "Rate of variation of densities") +
  geom_line(aes(x = time, y = ratioVar, color = Species))
plot_500.20_MF
```


```{r}
df_tab <- as.data.frame(model.output_250.20) %>%
  select(time, D.F_, D.M_) %>%
  mutate(group = "250.20",
         ID_group = "c")
D.F_scale_250.20 = scale_fun_F(df_tab)
D.M_scale_250.20 = scale_fun_M(df_tab)

df_tab$Foxes = df_tab$D.F_ / D.F_scale_250.20
df_tab$Mustelids = df_tab$D.M_ / D.M_scale_250.20

plot(df_tab$time, df_tab$Foxes)
plot(df_tab$time, df_tab$Mustelids)

df_plot_250.20_MF <- df_tab %>%
  gather(Species, ratioVar, c('Foxes', 'Mustelids'))

plot_250.20_MF <- ggplot(data = df_plot_250.20_MF) + theme_minimal() +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="time in year")+
  scale_color_manual(values = c("black", "grey70")) +
  labs(y = "Rate of variation of densities") +
  geom_line(aes(x = time, y = ratioVar, color = Species))
plot_250.20_MF
```


```{r}
df_tab <- as.data.frame(model.output_250.7.5) %>%
  select(time, D.F_, D.M_) %>%
  mutate(group = "250.7.5",
         ID_group = "d")
D.F_scale_250.7.5 = scale_fun_F(df_tab)
D.M_scale_250.7.5 = scale_fun_M(df_tab)

df_tab$Foxes = df_tab$D.F_ / D.F_scale_250.7.5
df_tab$Mustelids = df_tab$D.M_ / D.M_scale_250.7.5

plot(df_tab$time, df_tab$Foxes)
plot(df_tab$time, df_tab$Mustelids)

df_plot_250.7.5_MF <- df_tab %>%
  gather(Species, ratioVar, c('Foxes', 'Mustelids'))

plot_250.7.5_MF <- ggplot(data = df_plot_250.7.5_MF) + theme_minimal() +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="time in year")+
  scale_color_manual(values = c("black", "grey70")) +
  labs(y = "Rate of variation of densities") +
  geom_line(aes(x = time, y = ratioVar, color = Species))
plot_250.7.5_MF
```

```{r}
df_tab <- as.data.frame(model.output_50.7.5) %>%
  select(time, D.F_, D.M_) %>%
  mutate(group = "50.7.5",
         ID_group = "e")
D.F_scale_50.7.5 = scale_fun_F(df_tab)
D.M_scale_50.7.5 = scale_fun_M(df_tab)

df_tab$Foxes = df_tab$D.F_ / D.F_scale_50.7.5
df_tab$Mustelids = df_tab$D.M_ / D.M_scale_50.7.5

plot(df_tab$time, df_tab$Foxes)
plot(df_tab$time, df_tab$Mustelids)

df_plot_50.7.5_MF <- df_tab %>%
  gather(Species, ratioVar, c('Foxes', 'Mustelids'))

plot_50.7.5_MF <- ggplot(data = df_plot_50.7.5_MF) + theme_minimal() +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="time in year")+
  scale_color_manual(values = c("black", "grey70")) +
  labs(y = "Rate of variation of densities") +
  geom_line(aes(x = time, y = ratioVar, color = Species))
plot_50.7.5_MF
```

### Vole and Dead Vole

```{r}
## INITIAL VALUE
# scale_fun_Vd <- function(df){
#   df[df$time == 0, "D.Vd_"]
# }
# scale_fun_V <- function(df){
#   df[df$time == 0, "D.V_"]
# }
## SCALE WITH VAXIVAL
scale_fun_Vd <- function(df){
  max(df$D.Vd_)
}
scale_fun_V <- function(df){
  max(df$D.V_)
}
```



```{r}
df_tab <- as.data.frame(model.output_0.0) %>%
  select(time, D.Vd_, D.V_) %>%
  mutate(group = "0.0",
         ID_group = "a")
D.Vd_scale_0.0 = scale_fun_Vd(df_tab)
D.V_scale_0.0 = scale_fun_V(df_tab)

df_tab$dead_Voles = df_tab$D.Vd_ / D.Vd_scale_0.0
df_tab$Voles = df_tab$D.V_ / D.V_scale_0.0

plot(df_tab$time, df_tab$Voles)
plot(df_tab$time, df_tab$Voles)

df_plot_0.0_VVd <- df_tab %>%
  gather(Species, ratioVar, c('dead_Voles', 'Voles'))

plot_0.0_VVd <- ggplot(data = df_plot_0.0_VVd) + theme_minimal() +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="time in year")+
  scale_color_manual(values = c("black", "grey70")) +
  labs(y = "Rate of variation of densities") +
  geom_line(aes(x = time, y = ratioVar, color = Species))
plot_0.0_VVd
```

```{r}
df_tab <- as.data.frame(model.output_500.20) %>%
  select(time, D.Vd_, D.V_) %>%
  mutate(group = "500.20",
         ID_group = "b")
D.Vd_scale_500.20 = scale_fun_Vd(df_tab)
D.V_scale_500.20 = scale_fun_V(df_tab)

df_tab$dead_Voles = df_tab$D.Vd_ / D.Vd_scale_500.20
df_tab$Voles = df_tab$D.V_ / D.V_scale_500.20

plot(df_tab$time, df_tab$dead_Voles)
plot(df_tab$time, df_tab$Voles)

df_plot_500.20_VVd <- df_tab %>%
  gather(Species, ratioVar, c('dead_Voles', 'Voles'))

plot_500.20_VVd <- ggplot(data = df_plot_500.20_VVd) + theme_minimal() +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="time in year")+
  scale_color_manual(values = c("black", "grey70")) +
  labs(y = "Rate of variation of densities") +
  geom_line(aes(x = time, y = ratioVar, color = Species))
plot_500.20_VVd
```


```{r}
df_tab <- as.data.frame(model.output_250.20) %>%
  select(time, D.Vd_, D.V_) %>%
  mutate(group = "250.20",
         ID_group = "c")
D.Vd_scale_250.20 = scale_fun_Vd(df_tab)
D.V_scale_250.20 = scale_fun_V(df_tab)

df_tab$dead_Voles = df_tab$D.Vd_ / D.Vd_scale_250.20
df_tab$Voles = df_tab$D.V_ / D.V_scale_250.20

plot(df_tab$time, df_tab$dead_Voles)
plot(df_tab$time, df_tab$Voles)

df_plot_250.20_VVd <- df_tab %>%
  gather(Species, ratioVar, c('dead_Voles', 'Voles'))

plot_250.20_VVd <- ggplot(data = df_plot_250.20_VVd) + theme_minimal() +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="time in year")+
  scale_color_manual(values = c("black", "grey70")) +
  labs(y = "Rate of variation of densities") +
  geom_line(aes(x = time, y = ratioVar, color = Species))
plot_250.20_VVd
```


```{r}
df_tab <- as.data.frame(model.output_250.7.5) %>%
  select(time, D.Vd_, D.V_) %>%
  mutate(group = "250.7.5",
         ID_group = "d")
D.Vd_scale_250.7.5 = scale_fun_Vd(df_tab)
D.V_scale_250.7.5 = scale_fun_V(df_tab)

df_tab$dead_Voles = df_tab$D.Vd_ / D.Vd_scale_250.7.5
df_tab$Voles = df_tab$D.V_ / D.V_scale_250.7.5

plot(df_tab$time, df_tab$dead_Voles)
plot(df_tab$time, df_tab$Voles)

df_plot_250.7.5_VVd <- df_tab %>%
  gather(Species, ratioVar, c('dead_Voles', 'Voles'))

plot_250.7.5_VVd <- ggplot(data = df_plot_250.7.5_VVd) + theme_minimal() +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="time in year")+
  scale_color_manual(values = c("black", "grey70")) +
  labs(y = "Rate of variation of densities") +
  geom_line(aes(x = time, y = ratioVar, color = Species))
plot_250.7.5_VVd
```

```{r}
df_tab <- as.data.frame(model.output_50.7.5) %>%
  select(time, D.Vd_, D.V_) %>%
  mutate(group = "50.7.5",
         ID_group = "e")
D.Vd_scale_50.7.5 = scale_fun_Vd(df_tab)
D.V_scale_50.7.5 = scale_fun_V(df_tab)

df_tab$dead_Voles = df_tab$D.Vd_ / D.Vd_scale_50.7.5
df_tab$Voles = df_tab$D.V_ / D.V_scale_50.7.5

plot(df_tab$time, df_tab$dead_Voles)
plot(df_tab$time, df_tab$Voles)

df_plot_50.7.5_VVd <- df_tab %>%
  gather(Species, ratioVar, c('dead_Voles', 'Voles'))

plot_50.7.5_VVd <- ggplot(data = df_plot_50.7.5_VVd) + theme_minimal() +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="time in year")+
  scale_color_manual(values = c("black", "grey70")) +
  labs(y = "Rate of variation of densities") +
  geom_line(aes(x = time, y = ratioVar, color = Species))
plot_50.7.5_VVd
```

# Plot Join

```{r}
plot_join <- ggplot() +
  theme_minimal() +
  theme(#legend.position = c(0.13, 0.93), # c(0,0) bottom left, c(1,1) top-right.
        legend.position = "top",
        legend.background = element_rect(fill = "white",  colour = NA),
        legend.title = element_blank()
  ) +
  # theme(legend.position="none") +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="Time in year")+
  scale_color_manual(values = c("black", "grey50")) +
  labs(y = "Rate of variation of densities") +
  # Buffer
  geom_rect(
    data=data.frame(ID_group = c("a", "b", "c", "d", "e")),
    aes(xmin=0, xmax=365*10, ymin=-Inf, ymax=Inf), 
    alpha = 0.5, fill = 'black')
```


```{r}
df_join_VVd_temp <-bind_rows(
  list(df_plot_0.0_VVd,
       df_plot_500.20_VVd,
       df_plot_250.20_VVd,
       df_plot_250.7.5_VVd,
       df_plot_50.7.5_VVd),
  .id = "ID_group_num")
df_join_VVd <- df_join_VVd_temp  %>% mutate(Species = ifelse(Species == "dead_Voles", "Voles dead", Species))

plot_join_VVd <- plot_join + 
  geom_line(data = df_join_VVd,
            aes(x = time, y = ratioVar, color = Species), alpha = 0.5) +
  facet_wrap(~ID_group, ncol = 1)

plot_join_VVd
```

```{r}
df_join_MF <-bind_rows(
  list(df_plot_0.0_MF,
       df_plot_500.20_MF,
       df_plot_250.20_MF,
       df_plot_250.7.5_MF,
       df_plot_50.7.5_MF),
  .id = "ID_group_num")

plot_join_MF <- plot_join +
  geom_line(data = df_join_MF,
            aes(x = time, y = ratioVar, color = Species), alpha  = 0.5) +
  facet_wrap(~ID_group, ncol = 1)

plot_join_MF
```


## With colors

```{r}
# legend.position = c(.5, .5))
# z + theme(legend.background = element_rect(colour = "black")
plot_join <- ggplot() +
  theme_minimal() +
  theme(legend.position = c(0.13, 0.93), # c(0,0) bottom left, c(1,1) top-right.
        legend.background = element_rect(fill = "#ffffffaa", colour = NA),
        legend.title = element_blank()
  ) +
  # theme(legend.position="none") +
  scale_x_continuous(
      breaks = seq(0,max(times),length=11),
      labels=round(seq(0,max(times)/365,length=11),1),
      name="Time in year")+
  scale_color_manual(values = c("black", "grey50")) +
  labs(y = "Rate of variation of densities") +
  # Buffer
  geom_rect(
    data=data.frame(ID_group = c("a", "b", "c", "d", "e")),
    aes(xmin=0, xmax=365*10, ymin=-Inf, ymax=Inf), 
    alpha = 0.5, fill = 'grey')

y_min = -Inf # 1 
y_max = Inf # 1.2

b_seq = 365*c(10,   14.5,16.1,    21.2,22.9,   28,29.5,   34.9,36.5,   41.6,43.3,   48.3,50)
d_seq = 365*c(10,12.2,  14.8,17,  20.5,24, 27.2,30.4,   33.2,35.6,   39,42.7,  45.5,47.9,  50)
# VR Regulation
plot_join <- plot_join +
  geom_rect(data=data.frame(ID_group = "a"),
            aes(xmin=365*10, xmax=365*50, ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  # b
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[1], xmax=b_seq[2], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[3], xmax=b_seq[4], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[5], xmax=b_seq[6], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[7], xmax=b_seq[8], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[9], xmax=b_seq[10], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[11], xmax=b_seq[12], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  # d
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[2], xmax=d_seq[3], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[4], xmax=d_seq[5], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[6], xmax=d_seq[7], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[8], xmax=d_seq[9], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[10], xmax=d_seq[11], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[12], xmax=d_seq[13], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[14], xmax=d_seq[15], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#75E4E4') +
# VdR Regulation
  # b
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[2], xmax=b_seq[3], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[4], xmax=b_seq[5], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[6], xmax=b_seq[7], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[8], xmax=b_seq[9], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[10], xmax=b_seq[11], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  geom_rect(data=data.frame(ID_group = "b"),
            aes(xmin=b_seq[12], xmax=b_seq[13], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  # c
  geom_rect(data=data.frame(ID_group = "c"),
            aes(xmin=365*10, xmax=365*50, ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  # d
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[1], xmax=d_seq[2], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[3], xmax=d_seq[4], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[5], xmax=d_seq[6], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[7], xmax=d_seq[8], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[9], xmax=d_seq[10], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
   geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[11], xmax=d_seq[12], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
   geom_rect(data=data.frame(ID_group = "d"),
            aes(xmin=d_seq[13], xmax=d_seq[14], ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757') +
  # e
  geom_rect(data=data.frame(ID_group = "e"),
            aes(xmin=365*10, xmax=365*50, ymin=y_min, ymax=y_max),
            alpha = 0.5, fill = '#C15757')
```


```{r}
df_join_VVd_temp <-bind_rows(
  list(df_plot_0.0_VVd,
       df_plot_500.20_VVd,
       df_plot_250.20_VVd,
       df_plot_250.7.5_VVd,
       df_plot_50.7.5_VVd),
  .id = "ID_group_num")
df_join_VVd <- df_join_VVd_temp  %>% mutate(Species = ifelse(Species == "dead_Voles", "Voles dead", Species))

plot_join_VVd <- plot_join + 
  geom_line(data = df_join_VVd,
            aes(x = time, y = ratioVar, color = Species), alpha = 0.5) +
  facet_wrap(~ID_group, ncol = 1)

plot_join_VVd
```

```{r}
df_join_MF <-bind_rows(
  list(df_plot_0.0_MF,
       df_plot_500.20_MF,
       df_plot_250.20_MF,
       df_plot_250.7.5_MF,
       df_plot_50.7.5_MF),
  .id = "ID_group_num")

plot_join_MF <- plot_join +
  geom_line(data = df_join_MF,
            aes(x = time, y = ratioVar, color = Species), alpha  = 0.5) +
  facet_wrap(~ID_group, ncol = 1)

plot_join_MF
```



```{r}
plot_join <- grid.arrange(plot_join_MF,
             plot_join_VVd,
             ncol = 2)
ggsave(filename = "../manuscript/img/plot_join_MF.png", plot = plot_join_MF,
       width = 7, height = 9)
ggsave(filename = "../manuscript/img/plot_join_VVd.png", plot = plot_join_VVd,
       width = 7, height = 9)
ggsave(filename = "../manuscript/img/plot_join.png", plot = plot_join,
       width = 9, height = 7)
```

# TYPICAL PATTERNS FOR FIGURE

```{r param,echo=FALSE,warning=FALSE,include=FALSE}
times <- seq(from=0, to = 50*365, length = 50*365) #  30*5 = 5 months 
```

## a) Model 0-0


```{r model.output_0.0, echo=FALSE,warning=FALSE,comment=FALSE,message=FALSE, cache=TRUE}
init.p <- init(params$n)

# --------------------------- Modelisation -------------------
model.output_0.0 = ode(y=init.p,
                    times,
                    ode.broma.tritrophic, 
                    parms = params)
# --------------------------- Plot-------------------
graph_0.0 <- graphique_3(params$n,times,model.output_0.0)
graph_0.0
```

## b1) 500-20_1

```{r model.output_500.20, cache=TRUE}
params <- pars(n=1,
               LD.50.V = 0.7,
               LD.50.M = 2.5,
               LD.50.F = 0.5,
               H.V = 4,
               H.M = 4,
               H.F = 4,
               days.to.die.V = 5, 
               days.to.die.M = 5,
               days.to.die.F = 5)
init.p <- init(params$n)
# --------------------------- EVENEMENTS -------------------
root.event=condition(Vole.Level=500,Broma.Level=20*50)[[1]] # kg * mg/kg
event.func=condition(Vole.Level=500,Broma.Level=20*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_500.20_1 = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

graph_500.20_1 <- graphique_3(params$n,times,model.output_500.20_1)
graph_500.20_1
```

## b2) 500-20_2

```{r model.output_500.20, cache=TRUE}
params <- pars(n=1,
               LD.50.V = 2,
               LD.50.M = 2.5,
               LD.50.F = 0.5,
               H.V = 4,
               H.M = 4,
               H.F = 4,
               days.to.die.V = 5, 
               days.to.die.M = 5,
               days.to.die.F = 5)
init.p <- init(params$n)
# --------------------------- EVENEMENTS -------------------
root.event=condition(Vole.Level=500,Broma.Level=20*50)[[1]] # kg * mg/kg
event.func=condition(Vole.Level=500,Broma.Level=20*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_500.20_2 = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

graph_500.20_2 <- graphique_3(params$n,times,model.output_500.20_2)
graph_500.20_2
```

## b3) 500-20_3


```{r model.output_500.20, cache=TRUE}
params <- pars(n=1,
               LD.50.V = 4,
               LD.50.M = 2.5,
               LD.50.F = 0.5,
               H.V = 4,
               H.M = 4,
               H.F = 4,
               days.to.die.V = 5, 
               days.to.die.M = 5,
               days.to.die.F = 5)
init.p <- init(params$n)
# --------------------------- EVENEMENTS -------------------
root.event=condition(Vole.Level=500,Broma.Level=20*50)[[1]] # kg * mg/kg
event.func=condition(Vole.Level=500,Broma.Level=20*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_500.20_3 = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

graph_500.20_3 <- graphique_3(params$n,times,model.output_500.20_3)
graph_500.20_3
```

## c1) 250-20_1

```{r model.output_250.20, cache=TRUE}
params <- pars(n=1,
               LD.50.V = 2.5,
               LD.50.M = 2,
               LD.50.F = 7,
               H.V = 4,
               H.M = 4,
               H.F = 4,
               days.to.die.V = 5, 
               days.to.die.M = 5,
               days.to.die.F = 5)
init.p <- init(params$n)
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=250,Broma.Level=20*50)[[1]]
event.func = condition(Vole.Level=250,Broma.Level=20*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_250.20_1 = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

graph_250.20_1 <- graphique_3(params$n,times,model.output_250.20_1)
graph_250.20_1
```

## c2)250-20_2

```{r model.output_250.20, cache=TRUE}
params <- pars(n=1,
               LD.50.V = 2.5,
               LD.50.M = 7,
               LD.50.F = 7,
               H.V = 4,
               H.M = 4,
               H.F = 4,
               days.to.die.V = 5, 
               days.to.die.M = 5,
               days.to.die.F = 5)
init.p <- init(params$n)
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=250,Broma.Level=20*50)[[1]]
event.func = condition(Vole.Level=250,Broma.Level=20*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_250.20_2 = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

graph_250.20_2 <- graphique_3(params$n,times,model.output_250.20_2)
graph_250.20_2
```

## d1) 250-7.5_1

```{r model.output_250.7.5, cache=TRUE}
params <- pars(n=1,
               LD.50.V = 1.5,
               LD.50.M = 7,
               LD.50.F = 7,
               H.V = 4,
               H.M = 4,
               H.F = 4,
               days.to.die.V = 5, 
               days.to.die.M = 5,
               days.to.die.F = 5)
init.p <- init(params$n)
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=250,Broma.Level=7.5*50)[[1]]
event.func = condition(Vole.Level=250,Broma.Level=7.5*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_250.7.5_1 = ode(y=init.p,
                   times,
                   ode.broma.tritrophic,
                   # ode.broma.tritrophic_2nd, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)
graph_250.7.5_1 <-graphique_3(params$n,times,model.output_250.7.5_1)
graph_250.7.5_1
```

## d2) 250-7.5_2

```{r model.output_250.7.5, cache=TRUE}
params <- pars(n=1,
               LD.50.V = 2.5,
               LD.50.M = 7,
               LD.50.F = 7,
               H.V = 4,
               H.M = 4,
               H.F = 4,
               days.to.die.V = 5, 
               days.to.die.M = 5,
               days.to.die.F = 5)
init.p <- init(params$n)
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=250,Broma.Level=7.5*50)[[1]]
event.func = condition(Vole.Level=250,Broma.Level=7.5*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_250.7.5_2 = ode(y=init.p,
                   times,
                   ode.broma.tritrophic,
                   # ode.broma.tritrophic_2nd, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)
graph_250.7.5_2 <-graphique_3(params$n,times,model.output_250.7.5_2)
graph_250.7.5_2
```


## e1) Model 50-7.5_1

```{r model.output_50.7.5, cache=TRUE}
params <- pars(n=1,
               LD.50.V = 2,
               LD.50.M = 7,
               LD.50.F = 0.5,
               H.V = 4,
               H.M = 4,
               H.F = 4,
               days.to.die.V = 5, 
               days.to.die.M = 5,
               days.to.die.F = 5)
init.p <- init(params$n)
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=50,Broma.Level=7.5*50)[[1]]
event.func = condition(Vole.Level=50,Broma.Level=7.5*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_50.7.5_1 = ode(y = init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

graph_50.7.5_1 <- graphique_3(params$n,times,model.output_50.7.5_1)
graph_50.7.5_1
```

## e2) Model 50-7.5_2

```{r model.output_50.7.5, cache=TRUE}
params <- pars(n=1,
               LD.50.V = 2,
               LD.50.M = 7,
               LD.50.F = 2,
               H.V = 4,
               H.M = 4,
               H.F = 4,
               days.to.die.V = 5, 
               days.to.die.M = 5,
               days.to.die.F = 5)
init.p <- init(params$n)
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=50,Broma.Level=7.5*50)[[1]]
event.func = condition(Vole.Level=50,Broma.Level=7.5*50)[[2]]

# --------------------------- Modelisation -------------------
model.output_50.7.5_2 = ode(y = init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

graph_50.7.5_2 <- graphique_3(params$n,times,model.output_50.7.5_2)
graph_50.7.5_2
```

## FINAL PLOT

```{r}
pltDF = data.frame(
  time = c(model.output_0.0[, "time"],
           model.output_500.20_1[, "time"],
           model.output_500.20_2[, "time"],
           model.output_500.20_3[, "time"],
           model.output_250.20_1[, "time"],
           model.output_250.20_2[, "time"],
           model.output_250.7.5_1[, "time"],
           model.output_250.7.5_2[, "time"],
           model.output_50.7.5_1[, "time"],
           model.output_50.7.5_2[, "time"]),
  Voles = c(model.output_0.0[, "D.V_"],
           model.output_500.20_1[, "D.V_"],
           model.output_500.20_2[, "D.V_"],
           model.output_500.20_3[, "D.V_"],
           model.output_250.20_1[, "D.V_"],
           model.output_250.20_2[, "D.V_"],
           model.output_250.7.5_1[, "D.V_"],
           model.output_250.7.5_2[, "D.V_"],
           model.output_50.7.5_1[, "D.V_"],
           model.output_50.7.5_2[, "D.V_"]),
  Mustelids = c(model.output_0.0[, "D.M_"],
               model.output_500.20_1[, "D.M_"],
           model.output_500.20_2[, "D.M_"],
           model.output_500.20_3[, "D.M_"],
           model.output_250.20_1[, "D.M_"],
           model.output_250.20_2[, "D.M_"],
           model.output_250.7.5_1[, "D.M_"],
           model.output_250.7.5_2[, "D.M_"],
           model.output_50.7.5_1[, "D.M_"],
           model.output_50.7.5_2[, "D.M_"]),
  Foxes = c(model.output_0.0[, "D.F_"],
              model.output_500.20_1[, "D.F_"],
           model.output_500.20_2[, "D.F_"],
           model.output_500.20_3[, "D.F_"],
           model.output_250.20_1[, "D.F_"],
           model.output_250.20_2[, "D.F_"],
           model.output_250.7.5_1[, "D.F_"],
           model.output_250.7.5_2[, "D.F_"],
           model.output_50.7.5_1[, "D.F_"],
           model.output_50.7.5_2[, "D.F_"]),
  AR = c(model.output_0.0[, "C.soil_"],
         model.output_500.20_1[, "C.soil_"],
           model.output_500.20_2[, "C.soil_"],
           model.output_500.20_3[, "C.soil_"],
           model.output_250.20_1[, "C.soil_"],
           model.output_250.20_2[, "C.soil_"],
           model.output_250.7.5_1[, "C.soil_"],
           model.output_250.7.5_2[, "C.soil_"],
           model.output_50.7.5_1[, "C.soil_"],
           model.output_50.7.5_2[, "C.soil_"]),
  model = c(rep("a. A", nrow(model.output_0.0)),
            rep("b. B-1", nrow(model.output_500.20_1)),
            rep("c. B-2", nrow(model.output_500.20_2)),
            rep("d. B-3", nrow(model.output_500.20_3)),
            rep("e. C-1", nrow(model.output_250.20_1)),
            rep("f. C-2", nrow(model.output_250.20_2)),
            rep("g. D-1", nrow(model.output_250.7.5_1)),
            rep("h. D-2", nrow(model.output_250.7.5_2)),
            rep("i. E-1", nrow(model.output_50.7.5_1)),
            rep("j. E-2", nrow(model.output_50.7.5_2)))
)
# Convert brom in ppm / ha in kg/ha or AR
pltDF$AR = pltDF$AR /50 # 50ppm/kg

library(dplyr)
library(tidyr)
meltDF = gather(pltDF, "Population", "Density", c("AR", "Voles", "Mustelids", "Foxes"))

meltDF$Population = factor(meltDF$Population, levels = c("Foxes", "Mustelids", "Voles", "AR"))


meltDF1 = dplyr::filter(meltDF, model %in% c("a. A", "b. B-1", "e. C-1", "g. D-1", "i. E-1"))
dfRect1 =  data.frame(model = unique(meltDF1$model))
meltDF2 = dplyr::filter(meltDF, model %in% c("c. B-2", "d. B-3", "f. C-2", "h. D-2", "j. E-2"))
dfRect2 =  data.frame(model = unique(meltDF2$model))


plt_DF1 = ggplot() + theme_minimal() +
  theme(legend.position = "top") +
  labs(y = NULL)+
  scale_x_continuous(
      breaks = seq(0,max(meltDF$time),length=11),
      labels=round(seq(0,max(meltDF$time)/365,length=11),1),
      name=NULL)+
  scale_color_manual(values = c("#034df6", "#590786", "#502400", "#ff0000")) +
  # Population dynamics
  geom_line(data = meltDF1,
            aes(x = time, y = Density, color = Population)) +
  # Buffer
  geom_rect(
    data = dfRect1,
    aes(xmin=0, xmax=365*10, ymin=-Inf, ymax=Inf),
    alpha = 0.5, fill = 'grey') +
  facet_grid(Population ~ model, scale = "free")
plt_DF1

plt_DF2 = ggplot() + theme_minimal() +
  theme(legend.position = "none") +
  labs(y = NULL)+
  scale_x_continuous(
      breaks = seq(0,max(meltDF$time),length=11),
      labels=round(seq(0,max(meltDF$time)/365,length=11),1),
      name=NULL)+
  scale_color_manual(values = c("#034df6", "#590786", "#502400", "#ff0000")) +
  # Population dynamics
  geom_line(data = meltDF2,
            aes(x = time, y = Density, color = Population)) +
  # Buffer
  geom_rect(
    data=dfRect2,
    aes(xmin=0, xmax=365*10, ymin=-Inf, ymax=Inf),
    alpha = 0.5, fill = 'grey') +
  facet_grid(Population ~ model, scale = "free")
plt_DF2


library(gridExtra)
plt_DF = grid.arrange(plt_DF1,
                      plt_DF2,
                      nrow = 2,
                      bottom = "Time in year",
                      left = "Density [ind/ha] or AR amount [kg/ha]"
                      )

plt_DF

ggsave(plt_DF, file = "/home/vbaudrot/Documents/PACKAGES/trophToxNTO//manuscript/img/plot_join.png", width = 9, height = 7)

```



