---
title: "Sensitivity Analysis"
author: "Virgile Baudrot"
date: "18 février 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r,echo=FALSE,warning=FALSE,include=FALSE}
knitr::opts_chunk$set(fig.height = 6,
                      fig.width = 7)

library(trophToxNTO)
```

```{r}
times <- seq(from=0, to = 50*365, length = 1e4) ##  30*5 = 5 months 
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=250,Broma.Level=7.5*50)[[1]]
event.func = condition(Vole.Level=250,Broma.Level=7.5*50)[[2]]
```

# Single-wise parameters

### $r_V$

```{r r_V, cache=TRUE}
params <- pars(n=3)
params$r.V = varPercent_seq(params$r.V, 0.01, 10)

init.p <- init(params$n)

#### --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_Sensitivity <- tab_sensitivity2(model_output, params, key = "r.V")
```

## $K_V$

```{r K_V, cache=TRUE}
params <- pars(n=3)
params$K.V = varPercent_seq(params$K.V, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "K.V")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $a_M$ and $a_Md$

```{r a_M_a_Md, cache=TRUE}
params <- pars(n=3)
params$a.M = varPercent_seq(params$a.M, 0.01, 10)
params$a.Md = varPercent_seq(params$a.Md, 0.01, 10)


init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "a.M")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```


## $a_F$ and $a_Fd$

```{r a_F_a_Fd, cache=TRUE}
params <- pars(n=3)
params$a.F = varPercent_seq(params$a.F, 0.01, 10)
params$a.Fd = varPercent_seq(params$a.Fd, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "a.F")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $h_M$

```{r h_M, cache=TRUE}
params <- pars(n=3)
params$h.M = varPercent_seq(params$h.M, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "h.M")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $h_F$

```{r h_F, cache=TRUE}
params <- pars(n=3)
params$h.F = varPercent_seq(params$h.F, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "h.F")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $m_M$

```{r m_M, cache=TRUE}
params <- pars(n=3)
params$m.M = varPercent_seq(params$m.M, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "m.M")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $d$

```{r d, cache=TRUE}
params <- pars(n=3)
params$d = varPercent_seq(params$d, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "d")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $a_FM$

```{r a_FM, cache=TRUE}
params <- pars(n=3)
params$a.FM = varPercent_seq(params$a.FM, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "a.FM")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $r_F$

```{r r_F, cache=TRUE}
params <- pars(n=3)
params$r.F = varPercent_seq(params$r.F, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "r.F")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $K_F$

```{r K_F, cache=TRUE}
params <- pars(n=3)
params$K.F = varPercent_seq(params$K.F, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

tab <- table_df(model_output)

df_temp <- tab_sensitivity2(model_output, params, key = "K.F")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $e_M$

```{r e_M, cache=TRUE}
params <- pars(n=3)
params$e.M = varPercent_seq(params$e.M, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "e.M")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $LD_{50,V}$

```{r LD.50.V, cache=TRUE}
params <- pars(n=3)
params$LD.50.V = varPercent_seq(params$LD.50.V, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "LD.50.V")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $LD_{50,M}$

```{r LD.50.M, cache=TRUE}
params <- pars(n=3)
params$LD.50.M = varPercent_seq(params$LD.50.M, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "LD.50.M")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $LD_{50,F}$

```{r LD.50.F, cache=TRUE}
params <- pars(n=3)
params$LD.50.F = varPercent_seq(params$LD.50.F, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "LD.50.F")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## days to die $V$

```{r days.to.die.V, cache=TRUE}
params <- pars(n=3)
params$days.to.die.V = varPercent_seq(params$days.to.die.V, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "DTD.V")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## days to die $M$

```{r days.to.die.M, cache=TRUE}
params <- pars(n=3)
params$days.to.die.M = varPercent_seq(params$days.to.die.M, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "DTD.M")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## days to die $F$

```{r day.die.F, cache=TRUE}
params <- pars(n=3)
params$days.to.die.F = varPercent_seq(params$days.to.die.F, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "DTD.F")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $H.V$

```{r H.V, cache=TRUE}
params <- pars(n=3)
params$H.V = varPercent_seq(params$H.V, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "H.V")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```


## $H.M$

```{r H.M, cache=TRUE}
params <- pars(n=3)
params$H.M = varPercent_seq(params$H.M, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "H.M")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $H.F$

```{r H.F, cache=TRUE}
params <- pars(n=3)
params$H.F = varPercent_seq(params$H.F, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "H.F")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $B.V$

```{r B.V, cache=TRUE, eval=FALSE}
params <- pars(n=3)
params$B.V = varPercent_seq(params$B.V, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "B.V")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $B.M$

```{r B.M, cache=TRUE}
params <- pars(n=3)
params$B.M = varPercent_seq(params$B.M, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "B.M")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $B.F$

```{r B.F, cache=TRUE}
params <- pars(n=3)
params$B.F = varPercent_seq(params$B.F, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "B.F")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $max.intake.C$

```{r max.intake.C, cache=TRUE}
params <- pars(n=3)
params$max.intake.C = varPercent_seq(params$max.intake.C, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "max.intake.C")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $D50.intake.C$

```{r D50.intake.C, cache=TRUE}
params <- pars(n=3)
params$D50.intake.C = varPercent_seq(params$D50.intake.C, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "D50.intake.C")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```


## $eta.M$

```{r eta.M, cache=TRUE}
params <- pars(n=3)
params$eta.M = varPercent_seq(params$eta.M, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "eta.M")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```



## $eta.F$

```{r eta.F, cache=TRUE}
params <- pars(n=3)
params$eta.F = varPercent_seq(params$eta.F, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "eta.F")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $k.out.V$

```{r k.out.V, cache=TRUE}
params <- pars(n=3)
params$k.out.V = varPercent_seq(params$k.out.V, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "k.out.V")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```


## $k.out.M$

```{r k.out.M, cache=TRUE}
params <- pars(n=3)
params$k.out.M = varPercent_seq(params$k.out.M, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "k.out.M")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```



## $k.out.F$

```{r k.out.F, cache=TRUE}
params <- pars(n=3)
params$k.out.F = varPercent_seq(params$k.out.F, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "k.out.F")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

## $k.0$

```{r k.0, cache=TRUE}
params <- pars(n=3)
params$k.0 = varPercent_seq(params$k.0, 0.01, 10)

init.p <- init(params$n)

## --------------------------- Modelisation -------------------
model_output = ode(y=init.p,
                   times,
                   ode.broma.tritrophic, 
                   parms = params,
                   events = list(func = event.func, root = TRUE),
                   rootfun = root.event)

df_temp <- tab_sensitivity2(model_output, params, key = "k.0")

df_Sensitivity = rbind(df_Sensitivity, df_temp)
```

```{r}
save(df_Sensitivity, file = "data/df_Sensitivity.rda")
```


```{r}
load(file = "data/df_Sensitivity.rda")
library(ggplot2)
library(tidyr)
library(dplyr)

df_melt_Sensitivity = df_Sensitivity %>%
  mutate(SSE = SSE/(max(SSE, na.rm = T))) %>%
  rename(scale_SSE = SSE) %>%
  select(-param) %>%
  gather(key = "measure", value = "Value", -c("parameter", "range")) %>%
  spread(key = "range", value = "Value") %>%
  filter(!(parameter %in% c("H.M", "H.F", "H.V")))

levels(df_melt_Sensitivity$parameter) = rev(levels(df_melt_Sensitivity$parameter))

ggplot(data = df_melt_Sensitivity) + 
  theme_minimal() +
  labs(x = "Values", y = "Parameters") +
  geom_segment(aes(x = min , xend = max,
                   y = parameter, yend = parameter)) +
  facet_wrap(~ measure, nrow = 1, scales = "free_x") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

# Sobol Sensitivity Index

## Mixed parameters

```{r}
library(trophToxNTO)

times <- seq(from=0, to = 50*365, length = 1e4) ##  30*5 = 5 months 
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=250,Broma.Level=7.5*50)[[1]]
event.func = condition(Vole.Level=250,Broma.Level=7.5*50)[[2]]

params = pars(n=1)
init.p <- init(params$n)
# # Set fix parameters
# range_param = rbind(unlist(fix_pVar_pars(params,-0.1)), unlist(fix_pVar_pars(params,0.1)))
# ls_params = as.list(as.data.frame(range_param))
# ls_params_expand <- expand.grid(ls_params[2:ncol(range_param)])

# # Random parameters
ls_params_expand <- lapply(1:1000, function(i) rand_pVar_pars(params))

library(parallel)

ls_randSens <- mclapply(1:1e3, function(i){
  tryCatch({
    model_output = ode(y=init.p,
                       times,
                       ode.broma.tritrophic,
                       parms = ls_params_expand[[i]],
                       events = list(func = event.func, root = TRUE),
                       rootfun = root.event)
    df_temp <- tab_sensitivity(model_output, ls_params_expand[[i]])
    return(df_temp)},
    error=function(e) NULL)
}, mc.cores = 8)

df_randSens_Mixed <- dplyr::bind_rows(ls_randSens)
save(df_randSens_Mixed, file = "df_randSens_Mixed.rda")
```

## Mixed-1 parameters

```{r}
library(trophToxNTO)

times <- seq(from=0, to = 50*365, length = 1e4) ##  30*5 = 5 months 
# --------------------------- EVENEMENTS -------------------
root.event = condition(Vole.Level=250,Broma.Level=7.5*50)[[1]]
event.func = condition(Vole.Level=250,Broma.Level=7.5*50)[[2]]

params = pars(n=1)
init.p <- init(params$n)

n_val = expand.grid(n_it = 1:100, n_par = 1:32)
ls_p = lapply(1:3200, function(i){
   res = rep(0.1, 32) ; res[n_val$n_par[i]] = 0
   return(res)
  })

ls_params_expandCross <- lapply(1:3200, function(i) rand_pVar_pars(params, p = ls_p[[i]]))

library(parallel)

ls_randSens_Cross <- mclapply(1:3200, function(i){
  tryCatch({
    model_output = ode(y=init.p,
                       times,
                       ode.broma.tritrophic, 
                       parms = ls_params_expandCross[[i]],
                       events = list(func = event.func, root = TRUE),
                       rootfun = root.event)
    df_temp <- tab_sensitivity(model_output, ls_params_expandCross[[i]])
    return(df_temp)},
    error=function(e) NULL)
}, mc.cores = 8)

# mat_randSens <- do.call("rbind", ls_randSens)
df_randSens_Cross <- dplyr::bind_rows(ls_randSens_Cross)

df_randSens_Cross$n_it = n_val$n_it
df_randSens_Cross$n_par = n_val$n_par

save(df_randSens_Cross, file = "df_randSens_Cross.rda")
```

## global variance

```{r}
library(trophToxNTO)
library(dplyr)
# 1. Compute global variance
#load(file = "data/df_randSens_Mixed.rda")
load(file = "../simulation/df_randSens_Mixed_0_0.rda")
load(file = "../simulation/df_randSens_Mixed_500_20.rda")
load(file = "../simulation/df_randSens_Mixed_250_20.rda")
load(file = "../simulation/df_randSens_Mixed_250_7-5.rda")
load(file = "../simulation/df_randSens_Mixed_50_7-5.rda")

# 2. Compute variance of group
#load(file = "data/df_randSens_Cross.rda")
load(file = "../simulation/df_randSens_Cross_0_0.rda")
load(file = "../simulation/df_randSens_Cross_500_20.rda")
load(file = "../simulation/df_randSens_Cross_250_20.rda")
load(file = "../simulation/df_randSens_Cross_250_7-5.rda")
load(file = "../simulation/df_randSens_Cross_50_7-5.rda")

# 3. production
globalVariance = df_randSens_Mixed %>% 
  summarise(varMean_V = var(Mean_V),
            varMean_M = var(Mean_M),
            varMean_F = var(Mean_F),
            varV_inf50 = var(V_inf50),
            varnrb_AR = var(nrb_AR),
            varM_50AR = var(M_50AR, na.rm = T),
            varM_50natural = var(M_50natural, na.rm = T))
globalVariance


crossVariance_global = df_randSens_Cross %>%
  group_by(n_par) %>% 
  summarise(meanMean_V = mean(Mean_V),
            meanMean_M = mean(Mean_M),
            meanMean_F = mean(Mean_F),
            meanV_inf50 = mean(V_inf50),
            meannrb_AR = mean(nrb_AR),
            meanM_50AR = mean(M_50AR, na.rm = T),
            meanM_50natural = mean(M_50natural, na.rm = T)) %>%
  ungroup() %>%
  summarise(varMean_V = var(meanMean_V),
            varMean_M = var(meanMean_M),
            varMean_F = var(meanMean_F),
            varV_inf50 = var(meanV_inf50),
            varnrb_AR = var(meannrb_AR),
            varM_50AR = var(meanM_50AR, na.rm = T),
            varM_50natural = var(meanM_50natural, na.rm = T))

if(any(unique(df_randSens_Cross$n_par) != 1:32)){
  stop("NOT ALL PARAMETERS")
  # df_randSens_Cross[nrow(df_randSens_Cross)+1, "n_par"] <- 2
} 

crossVariance = df_randSens_Cross %>%
  group_by(n_par) %>% 
  summarise(varMean_V = var(Mean_V),
            varMean_M = var(Mean_M),
            varMean_F = var(Mean_F),
            varV_inf50 = var(V_inf50),
            varnrb_AR = var(nrb_AR),
            varM_50AR = var(M_50AR, na.rm = T),
            varM_50natural = var(M_50natural, na.rm = T))


# 3. Compute Sobol index
crossVariance_matrix = as.matrix(select(crossVariance, -n_par))
sobolSensitivityIndex_matrix = matrix(ncol = ncol(crossVariance_matrix), nrow=nrow(crossVariance_matrix))
for(i in 1:nrow(crossVariance_matrix)){
  sobolSensitivityIndex_matrix[i,] = crossVariance_matrix[i,] / as.matrix(globalVariance)
}
sobolSensitivityIndex = as.data.frame(sobolSensitivityIndex_matrix)
colnames(sobolSensitivityIndex) = colnames(crossVariance_matrix)


sobolSensitivityIndex$parameter = c("r.V", "K.V", "a.M", "a.F", "h.M", "h.F", "m.M", "d", "a.FM", "r.F", "K.F", "e.M", "LD.50.V", "LD.50.M", "LD.50.F", "dd.V", "dd.M", "dd.F", "H.V", "H.M", "H.F", "B.V", "B.M", "B.F", "Min", "Din", "eta.M", "eta.F", "k.out.V", "k.out.M", "k.out.F", "k.0")

levels(sobolSensitivityIndex$parameter) = factor(sobolSensitivityIndex$parameter, levels = c("r.V", "K.V", "a.M", "a.F", "h.M", "h.F", "m.M", "d", "a.FM", "r.F", "K.F", "e.M", "LD.50.V", "LD.50.M", "LD.50.F", "dd.V", "dd.M", "dd.F", "H.V", "H.M", "H.F", "B.V", "B.M", "B.F", "Min", "Din", "eta.M", "eta.F", "k.out.V", "k.out.M", "k.out.F", "k.0"))

sobolSensitivityIndex$parameter = c("$r_V$", "$K_V$", "$a_M$", "$a_F$", "$h_M$", "$h_F$", "$m_M$", "$d$", "$a_{FM}$", "$r_F$", "$K_F$", "$\\varepsilon_M$", "$LD_{50,V}$", "$LD_{50,M}$", "$LD_{50,F}$", "$dd_V$", "$dd_M$", "$dd_F$", "$H_V$", "$H_M$", "$H_F$", "$B_V$", "$B_M$", "$B_F$", "$M_{in}$", "$D_{in}$", "$\\eta_M$", "$\\eta_F$", "$k_{out,V}$", "$k_{out,M}$", "$k_{out,F}", "$k_0$")


sobolSensitivityIndex$parameter = c("r_V", "K_V", "a_M", "a_F", "h_M", "h_F", "m_M", "d", "a_{FM}", "r_F", "K_F", "\\varepsilon_M", "LD_{50,V}", "LD_{50,M}", "LD_{50,F}", "dd_V", "dd_M", "dd_F", "H_V", "H_M", "H_F", "B_V", "B_M", "B_F", "M_{in}", "D_{in}", "\\eta_M", "\\eta_F", "k_{out,V}", "k_{out,M}", "k_{out,F}", "k_0")

# --- plot
library(tidyr)
df_sobolIndex  = as.data.frame(sobolSensitivityIndex) %>%
  gather(measure, value, -parameter) %>%
  filter(!is.na(value))

library(ggplot2)
plt_sobolIndex <- ggplot() + theme_minimal() + 
  scale_y_discrete(limits=rev(unique(df_sobolIndex$parameter))) + 
  scale_fill_gradient2(low = "white", mid = "black", high = "red",
                       midpoint=1,
                       na.value = "grey",
                       name = "Sobol Index") +
  geom_tile(data = df_sobolIndex,
            aes(x = measure, y = parameter, fill = value))
plt_sobolIndex
# PICTURE: 680*430
ggsave(filename = "../manuscript/img/plt_sobolIndex_??_??.png",
       plot = plt_sobolIndex,
       width = 8, height = 5)
# --- 
# sobolSensitivityIndex_global = crossVariance_global / globalVariance
# sobolSensitivityIndex_global
```


```{r}
# library(GGally)
# # ggpairs(df_randSens[, 2:8])
# ggpairs(df_randSens[, c("Mean_V_set","Mean_M_set","Mean_F_set","V_inf50_set","nrb_AR_set","M_50AR_set","M_50natural_set")])
```

